### ISSUE TITLE
PyPI and pyc files?

### ISSUE THREAD

**Issue by guitarmanvt** [mlindemu/COMPSRest#1]
Hi. I noticed that you have a decent **setup.py** file, so I looked for this package on PyPI. I didn't find it. Do you plan to publish this to PyPI?

Also, I noticed several _.pyc files (and a *_**pycache***\* folder) in this repo. Usually, it's good to ignore those and not keep them in a repo, unless there's a reason (which you may have). You might want to remove them and update your **.gitignore**.

**Comment by mlindemu** [comment]
Hey, there are no plans to submit this repository to PyPi.  It's used internally at the University of South Florida to provide a REST interface to coastal and buoy environmental monitoring systems.  It has a very liberal MIT License applied to it.  Feel free to fork it if you would like to use it for your own purposes.

Thanks for the comment on the .gitignore.  I forgot to include it when I created the project.  I've removed the .pyc files and put a .gitignore in place.
